// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#ifndef REAL_THREAD_NOTIFICATIONS_DISPATCHER_H
#define REAL_THREAD_NOTIFICATIONS_DISPATCHER_H

#include "macro_utils/macro_utils.h"

#include "clds/tcall_dispatcher_ll.h"
#include "clds/tcall_dispatcher.h"
#include "thread_notifications_lackey_dll/thread_notifications_lackey_dll.h"

#include "../../inc/clds/thread_notifications_dispatcher.h"

#define R2(X) REGISTER_GLOBAL_MOCK_HOOK(X, real_##X);

#define REGISTER_THREAD_NOTIFICATIONS_DISPATCHER_GLOBAL_MOCK_HOOK() \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_REGISTER_TARGET(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_REGISTER_TARGET(real_THREAD_NOTIFICATION_CALL)) \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_UNREGISTER_TARGET(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_UNREGISTER_TARGET(real_THREAD_NOTIFICATION_CALL)) \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_DISPATCH_CALL(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_DISPATCH_CALL(real_THREAD_NOTIFICATION_CALL)) \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_CREATE(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_CREATE(real_THREAD_NOTIFICATION_CALL)) \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_MOVE(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_MOVE(real_THREAD_NOTIFICATION_CALL)) \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_INITIALIZE(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_INITIALIZE(real_THREAD_NOTIFICATION_CALL)) \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_INITIALIZE_MOVE(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_INITIALIZE_MOVE(real_THREAD_NOTIFICATION_CALL)) \
    REGISTER_GLOBAL_MOCK_HOOK(TCALL_DISPATCHER_ASSIGN(THREAD_NOTIFICATION_CALL), TCALL_DISPATCHER_LL_ASSIGN(real_THREAD_NOTIFICATION_CALL)) \
    MU_FOR_EACH_1(R2, \
        thread_notifications_dispatcher_init, \
        thread_notifications_dispatcher_deinit, \
        thread_notifications_dispatcher_get_call_dispatcher, \
    )

#include "umock_c/umock_c_prod.h"

TCALL_DISPATCHER_LL_TYPE_DECLARE(real_THREAD_NOTIFICATION_CALL, THREAD_NOTIFICATION_CALL, THREAD_NOTIFICATIONS_LACKEY_DLL_REASON, thread_notification_reason);

int real_thread_notifications_dispatcher_init(void);
void real_thread_notifications_dispatcher_deinit(void);

TCALL_DISPATCHER(THREAD_NOTIFICATION_CALL) real_thread_notifications_dispatcher_get_call_dispatcher(void);

#endif // REAL_THREAD_NOTIFICATIONS_DISPATCHER_H
