// Copyright (c) Microsoft. All rights reserved.

#define clds_hash_table_create real_clds_hash_table_create
#define clds_hash_table_destroy real_clds_hash_table_destroy
#define clds_hash_table_insert real_clds_hash_table_insert
#define clds_hash_table_delete real_clds_hash_table_delete
#define clds_hash_table_delete_key_value real_clds_hash_table_delete_key_value
#define clds_hash_table_remove real_clds_hash_table_remove
#define clds_hash_table_set_value real_clds_hash_table_set_value
#define clds_hash_table_find real_clds_hash_table_find
#define clds_hash_table_node_create real_clds_hash_table_node_create
#define clds_hash_table_node_inc_ref real_clds_hash_table_node_inc_ref
#define clds_hash_table_node_release real_clds_hash_table_node_release
#define clds_hash_table_snapshot real_clds_hash_table_snapshot